# Integration with KubeVela. See: https://www.cncf.io/blog/2020/12/22/argocd-kubevela-gitops-with-developer-centric-experience/
apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-kubeconfig
  namespace: argocd
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /home/tomas/.minikube/ca.crt
        extensions:
        - extension:
            last-update: Mon, 20 May 2024 22:21:10 CEST
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: cluster_info
        server: https://127.0.0.1:59450
      name: minikube
    contexts:
    - context:
        cluster: minikube
        extensions:
        - extension:
            last-update: Mon, 20 May 2024 22:21:10 CEST
            provider: minikube.sigs.k8s.io
            version: v1.31.2
          name: context_info
        namespace: default
        user: minikube
      name: minikube
    kind: Config
    users:
    - name: minikube
      user:
        client-certificate: /home/tomas/.minikube/profiles/minikube/client.crt
        client-key: /home/tomas/.minikube/profiles/minikube/client.key
