apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-app-backend-api
  description: The My-App Backend Service API
  tags:
    - restful
spec:
  type: openapi
  lifecycle: production
  owner: my-app-backend-subteam
  system: my-app
  definition: |
    openapi: 3.0.0
    info:
      title: My App API
      version: 1.0.0
    servers:
      - url: http://{host}:{port}
        variables:
          host:
            default: localhost # Replace with your server host
          port:
            default: 3000 # Replace with your server port
    paths:
      /:
        get:
          summary: Retrieve visitor count
          responses:
            '200':
              description: Visitor count retrieved successfully
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      count:
                        type: integer
                        description: The current visitor count
            '500':
              description: Failed to retrieve visitor count
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
                        description: Error message