apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-backend-dev 
  namespace: argocd
  labels:
    system-service: my-app-backend # This is for Backstage ArgoCD plugin
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading deletes when implementing the App of Apps pattern. If this isn't used, when you remove the application yaml from git, the application will be removed from ArgoCD but the resources will remain active in the cluster
spec:
  destination:
    namespace: my-app-dev 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/systems/my-app/backend
    helm:
      valueFiles:
        - environments/values-dev.yaml
    repoURL: https://github.com/tomasferrarisenda/backstage-minikube-lab-reloaded.git 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true