apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "configure k8s HPA for Deployment"
  name: horizontal-pod-autoscaler
spec:
  appliesToWorkloads:
    - frontend
    - backend
  schematic:
    cue:
      template: |
        outputs: hpa: {
            apiVersion: "autoscaling/v2beta2"
            kind:       "HorizontalPodAutoscaler"
            metadata: name: context.name
            spec: {
                scaleTargetRef: {
                    apiVersion: "apps/v1"
                    kind:       "Deployment"
                    name:       context.name
                }
                minReplicas: parameter.min
                maxReplicas: parameter.max
                metrics: [{
                    type: "Resource"
                    resource: {
                        name: "cpu"
                        target: {
                            type:               "Utilization"
                            averageUtilization: parameter.cpuUtil
                        }
                    }
                }]
            }
        }
        parameter: {
            min:     *1 | int
            max:     *4 | int
            cpuUtil: *80 | int
        }
