apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nginx
spec:
  components:
  - name: nginx
    properties:
      image: nginx:1.20.0
      ports:
      - expose: true
        port: 80
    traits:
    - properties:
        http:
          /: 80
      type: gateway
    type: webservice