apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-app-redis
  description: My-App Redis Databse
  annotations:
    backstage.io/techdocs-ref: dir:.
    # backstage.io/kubernetes-id: my-app-redis # This annotation doesn't work in objects of kind Resource. It only works in objects of kind Component. Our Redis deployment is registered as a Resource in Backstege catalog, so we can't use this annotation unless we change the kind of the object to Component.
    github.com/project-slug: tomasferrarisenda/backstage-minikube-lab-reloaded
    argocd/app-selector: system-service=my-app-redis # This is for Backstage ArgoCD plugin. Can also use argocd/app-name
    grafana/dashboard-selector: "tags @> 'linux'" # The following selector will return dashboards that have a 'linux' tag
    # grafana/overview-dashboard: 'http://localhost:8082/d/k8s_views_global/kubernetes-views-global' # I couldn't make this work. Got error: Refused to frame 'https://localhost:8082/' because it violates the following Content Security Policy directive: "frame-src 'self' http://localhost:8082".
  tags:
    - redis 
  links:
    - title: Documentation
      url: https://github.com/tomasferrarisenda/backstage-minikube-lab-reloaded
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://grafana.domain.com/
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://grafana.domain.com/
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: database
  lifecycle: production
  owner: my-app-redis-subteam
  system: my-app