name: Build & push my-app-backend image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'application-code/my-app/backend/**'

env:
  SYSTEM: my-app
  SERVICE: backend

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.SYSTEM }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: application-code/${{ env.SYSTEM }}/${{ env.SERVICE }}
          dockerfile: application-code/${{ env.SYSTEM }}/${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

# RELOADED
  # update-image-tag:
  #   name: Update image tag
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
