apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: frontend
  annotations:
    definition.oam.dev/description: "It's frontend and I'm too lazy to write descriptions"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    kube:
      template:
        apiVersion: apps/v1
        kind: Deployment
        spec:
          selector:
            matchLabels:
              app.oam.dev/component: frontend
          template:
            metadata:
              labels:
                app.oam.dev/component: frontend
            spec:
              containers:
              - name: frontend
                ports:
                - containerPort: 80
                livenessProbe:
                  httpGet:
                    path: /
                    port: 80
                readinessProbe:
                  httpGet:
                    path: /
                    port: 80
      parameters:
      - name: name
        required: true
        type: string
        fieldPaths:
        - metadata.name
        - metadata.labels.app
        - spec.selector.matchLabels.app
        - spec.template.metadata.labels.app
      - name: image
        required: true
        type: string
        fieldPaths:
        - spec.template.spec.containers[0].image
      - name: port
        required: false
        type: number
        fieldPaths:
        - spec.template.spec.containers[0].ports[0].containerPort
        - spec.template.spec.containers[0].livenessProbe.httpGet.port
        - spec.template.spec.containers[0].readinessProbe.httpGet.port
